server:
  port: 8001
  servlet:
    context-path: /register
spring:
  application:
      name: FEBS-Register
  security:
    user:
      name: febs
      password: 123456
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    initial-instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
